import dataset.AesEncryption;
import java.io.File;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PERUMAL
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setMaximizedBounds(new java.awt.Rectangle(1100, 700, 1100, 700));
        setMaximumSize(new java.awt.Dimension(2000, 900));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login Form");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 90, 420, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("ACCOUNT NO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 160, 100, 30);

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(150, 240, 90, 30);

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 390, 80, 30);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 390, 90, 30);

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("CREATE ACCOUNT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 20, 420, 50);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(260, 240, 90, 30);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 430, 210, 20);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(140, 160, 320, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("LEVEL1");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 270, 110, 30);

        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyTyped(evt);
            }
        });
        jPanel1.add(jPasswordField3);
        jPasswordField3.setBounds(370, 240, 90, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(260, 310, 90, 30);

        jPasswordField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField4KeyTyped(evt);
            }
        });
        jPanel1.add(jPasswordField4);
        jPasswordField4.setBounds(150, 310, 90, 30);

        jPasswordField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField5KeyTyped(evt);
            }
        });
        jPanel1.add(jPasswordField5);
        jPasswordField5.setBounds(370, 310, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(590, 90, 480, 520);

        jLabel9.setBackground(new java.awt.Color(0, 204, 204));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("THREE FACTOR AUTHENTICATION TO SAFEGUARD AN ONLINE TRANSACTION");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 20, 1030, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3d-cube-wallpaper_05.jpg"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel11.setMaximumSize(new java.awt.Dimension(1000, 524));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 90, 560, 520);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        Register rs=new Register();
        rs.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
              AesEncryption asc=new AesEncryption();
              String status="Active";
           int v=0;
            
            //Class.forName("com.mysql.jdbc.Driver");
            //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/security","root","root");
            
            DBconnect co=new DBconnect();
            Connection con=co.connect();
            
            Statement st=con.createStatement();
            Statement ob=con.createStatement();
         if((jPasswordField1.getText().equals(""))||(jPasswordField2.getText().equals(""))||(jPasswordField3.getText().equals(""))||(jPasswordField4.getText().equals(""))||(jPasswordField5.getText().equals(""))||(jTextField1.getText().equals(""))||(jTextField2.getText().equals(""))){
          
                JOptionPane.showMessageDialog(null,"Please Enter All Values");
          
         }else{
             
                ResultSet rs=st.executeQuery("select * from register where account='"+asc.toEncrypt(jPasswordField2.getText().getBytes())+"' and l1pwd = '"+asc.toEncrypt(jPasswordField1.getText().getBytes())+"'and l1rgd = '"+asc.toEncrypt(jTextField2.getText().getBytes())+"'and l1ver= '"+asc.toEncrypt(jPasswordField3.getText().getBytes())+"' and l2pwd = '"+asc.toEncrypt(jPasswordField4.getText().getBytes())+"'and l2rgd = '"+asc.toEncrypt(jTextField1.getText().getBytes())+"'and l2ver= '"+asc.toEncrypt(jPasswordField5.getText().getBytes())+"'  and status='"+asc.toEncrypt(status.getBytes())+"'");
            if(rs.next()){
           
             v=1;
            }
                 
                    
            
            if((v==1)){
           
//                   ResultSet rs1=st.executeQuery("select * from register where account='"+asc.toEncrypt(jPasswordField2.getText().getBytes())+"' and l1pwd = '"+jPasswordField1.getText()+"'and l1rgd = '"+asc.toEncrypt(jTextField2.getText().getBytes())+"'and l1ver= '"+jPasswordField3.getText()+"' and l2pwd = '"+jPasswordField4.getText()+"'and l2rgd = '"+jTextField2.getText()+"'and l2ver= '"+jPasswordField5.getText()+"'  and status='Active'");
//            if(rs1.next()){
//           
//             v=1;
//            }
//                 
//                    
//            
//            if((v==1)){
//           
//                JOptionPane.showMessageDialog(null,"Login Successfully");
//               
//                 this.setVisible(false);
//                 Home1 as=new Home1(jPasswordField2.getText());
//                 as.setVisible(true);
//            }else{
//          
//             
//                JOptionPane.showMessageDialog(null,"Login Failed");
//                
//               this.setVisible(true);
//            }
          
               //String wer=asc.toEncrypt(jPasswordField2.getText().getBytes());
                 this.setVisible(false);
                 Home1 as=new Home1(jPasswordField2.getText());
                 as.setVisible(true);
            }else{
          
             
                JOptionPane.showMessageDialog(null,"Login Failed");
                
               this.setVisible(true);
            }
          
         }
         
      }catch(Exception ex){
          ex.printStackTrace();
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPasswordField2.setText("");
        jTextField2.setText("");
        jPasswordField1.setText("");
        jTextField1.setText("");
        jPasswordField3.setText("");
        jPasswordField4.setText("");
        jPasswordField5.setText("");
          this.setVisible(false);
          Home rs11=new Home();
          rs11.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
       if(!(Character.isAlphabetic(c) || (c==evt.VK_BACK_SPACE) || c==evt.VK_DELETE )) {
        evt.consume();  // ignore the event if it's not an alphabet
    }
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jPasswordField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField5KeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
       if(!(Character.isAlphabetic(c) || (c==evt.VK_BACK_SPACE) || c==evt.VK_DELETE )) {
        evt.consume();  // ignore the event if it's not an alphabet
    }
    }//GEN-LAST:event_jPasswordField5KeyTyped

    private void jPasswordField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if ( ((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();  // if it's not a number, ignore the event
        }
    }//GEN-LAST:event_jPasswordField3KeyTyped

    private void jPasswordField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField4KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if ( ((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();  // if it's not a number, ignore the event
        }
    }//GEN-LAST:event_jPasswordField4KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
